// <auto-generated />
using System;
using InformationProcessSupport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformationProcessSupport.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230113174016_ChangeNullabeTypeExitTimeInStatisticsEntity")]
    partial class ChangeNullabeTypeExitTimeInStatisticsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InformationProcessSupport.Data.Channels.ChannelEntity", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ChannelId"));

                    b.Property<decimal>("AlternateKey")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChannelId");

                    b.HasAlternateKey("AlternateKey");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Statistics.StatisticEntity", b =>
                {
                    b.Property<int>("StatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatisticId"));

                    b.Property<string>("Attendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("CameraOperationTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CameraTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CameraTurnOnTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<TimeSpan>("ConnectionTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("MicrophoneOperatingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("MicrophoneTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MicrophoneTurnOnTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StreamOperationTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("StreamTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StreamTurnOnTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("StatisticId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Users.UserEntity", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"));

                    b.Property<decimal>("AlternateKey")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("GuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasAlternateKey("AlternateKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Statistics.StatisticEntity", b =>
                {
                    b.HasOne("InformationProcessSupport.Data.Channels.ChannelEntity", "ChannelEntity")
                        .WithMany("StatisticEntities")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InformationProcessSupport.Data.Users.UserEntity", "UserEntity")
                        .WithMany("StatisticsEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Channels.ChannelEntity", b =>
                {
                    b.Navigation("StatisticEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Users.UserEntity", b =>
                {
                    b.Navigation("StatisticsEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
