// <auto-generated />
using System;
using InformationProcessSupport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformationProcessSupport.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InformationProcessSupport.Data.Channels.ChannelEntity", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ChannelId"));

                    b.Property<decimal>("AlternateKey")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChannelId");

                    b.HasAlternateKey("AlternateKey");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Statistics.StatisticEntity", b =>
                {
                    b.Property<int>("StatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatisticId"));

                    b.Property<string>("Attendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<TimeSpan>("ConnectionTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("StatisticId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.CameraActions.CameraActionsEntity", b =>
                {
                    b.Property<int>("CameraActionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraActionsId"));

                    b.Property<TimeSpan?>("CameraOperationTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("CameraTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CameraTurnOnTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatistisId")
                        .HasColumnType("int");

                    b.HasKey("CameraActionsId");

                    b.HasIndex("StatistisId");

                    b.ToTable("CameraActionsEntity");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.MicrophoneActions.MicrophoneActionsEntity", b =>
                {
                    b.Property<int>("MicrophoneTimeEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MicrophoneTimeEntityId"));

                    b.Property<TimeSpan?>("MicrophoneOperatingTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("MicrophoneTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MicrophoneTurnOnTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatistisId")
                        .HasColumnType("int");

                    b.HasKey("MicrophoneTimeEntityId");

                    b.HasIndex("StatistisId");

                    b.ToTable("MicrophoneActionsEntity");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.SelfDeafenedActions.SelfDeafenedActionsEntity", b =>
                {
                    b.Property<int>("SelfDeafenedActionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SelfDeafenedActionsId"));

                    b.Property<TimeSpan?>("SelfDeafenedOperationTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("SelfDeafenedTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SelfDeafenedTurnOnTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatistisId")
                        .HasColumnType("int");

                    b.HasKey("SelfDeafenedActionsId");

                    b.HasIndex("StatistisId");

                    b.ToTable("SelfDeafenedActionsEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.StreamActions.StreamActionsEntity", b =>
                {
                    b.Property<int>("StreamActionsEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreamActionsEntityId"));

                    b.Property<int>("StatistisId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StreamOperationTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("StreamTurnOffTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StreamTurnOnTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StreamActionsEntityId");

                    b.HasIndex("StatistisId");

                    b.ToTable("StreamActionsEntity");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Users.UserEntity", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"));

                    b.Property<decimal>("AlternateKey")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("GuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Statistics.StatisticEntity", b =>
                {
                    b.HasOne("InformationProcessSupport.Data.Channels.ChannelEntity", "ChannelEntity")
                        .WithMany("StatisticEntities")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InformationProcessSupport.Data.Users.UserEntity", "UserEntity")
                        .WithMany("StatisticsEntity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.CameraActions.CameraActionsEntity", b =>
                {
                    b.HasOne("InformationProcessSupport.Data.Statistics.StatisticEntity", "StatisticEntities")
                        .WithMany("CameraActionsEntity")
                        .HasForeignKey("StatistisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.MicrophoneActions.MicrophoneActionsEntity", b =>
                {
                    b.HasOne("InformationProcessSupport.Data.Statistics.StatisticEntity", "StatisticEntities")
                        .WithMany("MicrophoneActionsEntity")
                        .HasForeignKey("StatistisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.SelfDeafenedActions.SelfDeafenedActionsEntity", b =>
                {
                    b.HasOne("InformationProcessSupport.Data.Statistics.StatisticEntity", "StatisticEntities")
                        .WithMany("SelfDeafenedActionsEntities")
                        .HasForeignKey("StatistisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.TimeOfActionsInTheChannel.StreamActions.StreamActionsEntity", b =>
                {
                    b.HasOne("InformationProcessSupport.Data.Statistics.StatisticEntity", "StatisticEntities")
                        .WithMany("StreamActionsEntity")
                        .HasForeignKey("StatistisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatisticEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Channels.ChannelEntity", b =>
                {
                    b.Navigation("StatisticEntities");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Statistics.StatisticEntity", b =>
                {
                    b.Navigation("CameraActionsEntity");

                    b.Navigation("MicrophoneActionsEntity");

                    b.Navigation("SelfDeafenedActionsEntities");

                    b.Navigation("StreamActionsEntity");
                });

            modelBuilder.Entity("InformationProcessSupport.Data.Users.UserEntity", b =>
                {
                    b.Navigation("StatisticsEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
